sudo: false
language: ruby
script: "bundle exec rake $CHECK"
notifications:
  email: false
rvm:
  - 2.3.1
  - 2.2.5
  - 2.1.9
  - 2.0.0
env:
#  - "CHECK=test"
  - "CHECK=rubocop"

matrix:
  exclude:
    - rvm: 2.2.5
      env: "CHECK=rubocop"
    - rvm: 2.1.9
      env: "CHECK=rubocop"
    - rvm: 2.0.0
      env: "CHECK=rubocop"
